### ISSUE TITLE
Platform an Distribution detector

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#117]
Hyperion needs more intelligence if we want to automate the grabber selection.

If found this, but the interesting part ist just available with Qt5.4 and hostname with QT5.6
http://doc.qt.io/qt-5/qsysinfo.html

So wie end up with hacking?
/cpu/procinfo (for Pi BCM version), lsb_release and uname?

OS=$(lsb_release -si)
ARCH=$(uname -m | sed 's/x86_//;s/i[3-6]86/32/')
VER=$(lsb_release -sr)
HOST=$(uname --nodename)

This information could be also pushed to the webinterface and a minified version for statistic purposes.

**Comment by redPanther** [comment]
ok lets sort a bit out here. We have to make at least 3 builds:
- linux x86 64bit
- linux armv6 32bit
- osx

if we take raspi 3 seriously, then we have to build for:
linux armv8 64bit
(note: some ws2812 stuff might not 64bit compatible)

lets take the first 3:
**osx** -> platform and hardware is clear before compiling (cmake), so no runtime detection necessary.

**linux x86 64bit** -> dispmanx and pwm stuff, must be disabled in this build.
Only choice on this platform is x11,fb,v4l
we had to check if X11 is running. If so, start that grabber, otherwise try framebuffer (fb). If a /dev/video* device is there, take first working device, take it for v4l and start it.

we need detection for:
- X11
- v4l2

**linux armv6 32bit** -> 
available grabbers: x11, fb, v4l, dispmanx, amlogic
ok on this platform we need some detection:
- X11
- v4l2
- board (cpu) type: raspi, amlogic (wetek), other

CPU type we have to get from /proc/cpuinfo. This is the default way.
The logic:

**for all boards:**
 If a /dev/video* device is there, take first working device, take it for v4l and start it.

**raspi**
take dispmanx (x11 and fb are possible, but make no sense because dispmanx is a better/faster interface for grabbing)

**amlogic**
take amlogic driver, if that fails we had to check if X11 is running, if so take it, otherwise choose fb

**other**
we had to check if X11 is running. If so, start that grabber, otherwise try framebuffer (fb).


**result:**
we need a checks for:
- x11
- v4l
- cpu/board type

no other stuff is needed. BTW, we getting the hostname via posix function gethostname() already for zeroconf

**Comment by redPanther** [comment]
Did we have something to do here? Grabber and v4l  selection is already done.  If needed for statistics we can expose kernel, distro and build flags.

**Comment by brindosch** [comment]
There is one last question: framegrabber section. I think it's not worth to implement this in a way like led devices. But for the ui i need to know on which platform it runs, to hide options and explanations accordingly.

**Comment by brindosch** [comment]
Regarding stats i already requested this from @Paulchen-Panther with a good research base (where to find what)

**Comment by penfold42** [comment]
The webui shouldn't be platform dependent - can we get the possible grabbers at run time from hyperiond ?
