### ISSUE TITLE
Can no longer configure frame buffer device

### ISSUE THREAD

**Issue by washcroft** [hyperion-project/hyperion.ng#1266]
- [x] I confirm that this is an issue rather than a question.

## Bug report

@Lord-Grey 

PR #1073 unnecessarily removed the device field from the UI.

I have multiple video frame buffers (GPUs), and the video I want to capture isn't displayed on /dev/fb0. I used to be able to specify the correct frame buffer device here (fb1 for me), but now it's hardcoded (defaulted) to fb0. Even though the core supports specifying the device to read from, this PR had removed the field to configure the device name in the UI.

**Comment by Lord-Grey** [comment]
@washcroft The current state reflects an intermediary development state given that we are further improving grabbers…
I am currently having some updated framegrabber code available, but due to limited time on my side, I was not able to finish it up. With the next release, we are looking to close the known gap on framegrabber, amlogic and dispmanx.
I ask for your patience until then…

**Comment by Lord-Grey** [comment]
@washcroft I am closing the issue, as alpha10 was released. Please check and report back in case the issue persists.
