### ISSUE TITLE
Hyperion does not reconnect to WLED through adalight

### ISSUE THREAD

**Issue by SunnyMoo** [hyperion-project/hyperion.ng#1302]
- [x] I confirm that this is an issue rather than a question.

## Bug report
After controller being turned off/on Hyperion does not reconnect to WLED through adalight. WLED acts as standalone.
Playing with adalight settings and sometimes turning off/on First LED Hardware instance through dashboard resolve the issue until next reboot.
I think it bugs after this message (not sure): [hyperiond LEDDEVICE] (ERROR) Device disabled, device 'adalight' signals error: 'Rs232 SerialPortError: Le p�riph�rique ne reconna�t pas la commande.'
Tested with WLED 12 to lastet and Hyperion stable to latest.  Also tested HyperHDR with same issue.
Some debug log attached.
Thank you !

#### Steps to reproduce
Set protocol to adalight.
Turn controller power off then on.

#### What is expected?
Hyperion should reconnect automatically to WLED after controller reboot.

#### What is actually happening?
After controller being powered off then on, WLED doesn't receive Hyperion stream any more.

#### System

Hyperion Server: 
- Build:           (HEAD detached at b1a4e95c) (Paulchen-Panther-975f969a/b1a4e95c-1626550299)
- Build time:      Jul 17 2021 20:53:38
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.10
- UI Lang:         auto (BrowserLang: en-US)
- UI Access:       expert
- Avail Capt:      v4l2,qt,dx
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Windows 10 Version 2009
- Architecture:   x86_64
- Kernel:         winnt (10.0.19043 (WS: 64))
- Qt Version:     5.15.0
- Python Version: 3.9.6
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
[hyperion debug log 1.txt](https://github.com/hyperion-project/hyperion.ng/files/6970968/hyperion.debug.log.1.txt)
[hyperion debug log 2.txt](https://github.com/hyperion-project/hyperion.ng/files/6970969/hyperion.debug.log.2.txt)
[hyperion debug log 3.txt](https://github.com/hyperion-project/hyperion.ng/files/6970970/hyperion.debug.log.3.txt)

**Comment by Lord-Grey** [comment]
@SunnyMoo Just checking, if I got the problem right…
You are saying that you run WLED on a controller which is connected via USB.

In case you power of the WLED Controller (or disconnect it), the error occurs that Hyperion cannot write to it.

You expect that when powering on the WLED controller, Hyperion recognizes this (however this is done…) and continues processing.

In case the LED Device is in error you can enable it manually and the device continues working (which is in line with the current design).

Is this a fair summary?

**Comment by SunnyMoo** [comment]
Hi @Lord-Grey,

Not sure, sorry I'm not english native.

My ESP32 controller is connected on my monitor through USB and is powered by this USB.
When I turn my monitor off it turns controller off, when monitor is turned on controller turns on.

I'm not sure if I expect Hyperion to know if controller is on or off as I don't know how it works underhood.
I stupidly thought that Hyperion was blindly streaming either controller can receive or not so that when controller turns back on it would receive Hyperion stream again.

Issue is, after controller being turned off/on, Hyperion does no more stream to WLED (WLED is in standalone mode) until -for example- I change adalight delay after connect from 0 to 1 (or anything else) and save.
Doing this acts like a connection retore between Hyperion and WLED.

Don't hesitate to ask for clarify.
Thank you !

**Comment by Lord-Grey** [comment]
@SunnyMoo No worries. As we both are not native speakers, I wanted to first understand where you are coming from.
The summary well describes the situation.
Hyperion is currently not in the position to just reopen a closed USB device (that happens when you turn off the monitor).
To recover from that situation, Hyperion would need to continuously trying to reopen the port. For now this is not supported, to ensure that errors can be detected by the user and system resources are not wasted.

Nevertheless, there is no need that you change the configuration to restart the device!
Either on the dashboard or remote control screen just switch on the LED Device again.
If the device can be used, it stays on and streaming happens. In case of error, it turns off again.

If you PC is running through and you only switch off the monitor, maybe you want to connect WLED to the PC (and e.g. the mouse to monitor) as a workaround….

**Comment by Lord-Grey** [comment]
> Turning led instance off/on works like 1 on 10 times

Could you share a log when it is not working?

> I'll give a try to wifi instead of adalight 

If Hyperion looses the network connection after you switched off the controller, you will have the same problem again.
Currently, there are no retries.

**Comment by SunnyMoo** [comment]
Hey @Lord-Grey,

Each time I turn off/on my controller Hyperion reconnects to WLED (protocol wled)
The only issue I have with WLED over wifi is very short connection losses but it's due to bad wifi signal here.

Here's the log you asked for:
[hyperion debug log 4.txt](https://github.com/hyperion-project/hyperion.ng/files/6975877/hyperion.debug.log.4.txt)

**Comment by Lord-Grey** [comment]
@SunnyMoo Maybe we are talking different things, or I did not get your point....

> Turning led instance off/on works like 1 on 10 times

I was under the assumption, you were referring to the fact that the switch on/off for WLED as USB/Adalight device is not working. That point I wanted to clarify, if this is really the case?

If you run WLED via WIFI using the LED-Device type = WLED and have a bad Wifi, I can follow that this might not work stable.
But then I would expect to see WLED errors in the log and not adalight ones....

The timeout in the log might be due to the fact that you are running with a too high Baud rate, to low latch-time (or using a bad USB cable). Or you disconnected the controller...?

**Comment by SunnyMoo** [comment]
@Lord-Grey I did not logged wifi unstability because it's due to my thick walls, neighboors hotspots and router far away Hyperion is working as expected in this configuration.

About "Turning led instance off/on works like 1 on 10 times" I was meaning that, when using adalight, turning "First LED Hardware instance" on/off in the dashboard does not reconnect Hyperion to WLED most of the time. (log #4)
However in this case changing an adalight setting reconnects Hyperion to WLED almost everytime.
