### ISSUE TITLE
Additional cablings for LED walls/matrix

### ISSUE THREAD

**Issue by ngrosc** [hyperion-project/hyperion.ng#1420]
## Feature request

Currently, there are two cabling options for a LED wall: snake and parallel.
Both of them start at a given point and continue to the other side of the line (input parameter). Then it changes the line given to the cabling parameter. But at the end, all eight combinations are filling the line horizontally and jump then to the next line.
As some setups has cablings where the path is vertically, its not possible to map these cablings to an offering in hyperion. 
It would be great, to also support horizontal cablings with some additional cabling offerings, lets say vertical snake and vertical parallel

#### What problem does this feature solve?
Adds support for other cabling directions than the current offered ones

#### What does the proposed API look like?
Same as the current one, just extended by additional values for the parameter

#### How should this be implemented in your opinion?
Implement the new cabling options in the "core" software and offer config options for selecting them

#### Are you willing to work on this yourself?
As long as I can somehow contribute in python yes, other languages I'm not very familiar

**Comment by Lord-Grey** [comment]
@ngrosc Thanks for the suggested feature!

If you are familiar with Git and building Hyperion yourself, you can use my [development branch](https://github.com/Lord-Grey/hyperion.ng/tree/UI) for testing.

Otherwise you need waiting for an upcoming release.

Here is a "teaser":

![image](https://user-images.githubusercontent.com/48840279/150648976-36151be2-3321-46ea-9406-210e0ab45134.png)

**Comment by ngrosc** [comment]
@LordGrey: great, thanks

just installed it and its working like a charm.



Am Sa., 22. Jan. 2022 um 18:23 Uhr schrieb LordGrey <
***@***.***>:
