### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by darkcheater** [hyperion-project/hyperion.ng#1425]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I have to restart hyperion from time to time because eventually, it will eat all my memory.

#### Steps to reproduce
Start hyperion and use it. I use effects for usual lighting and for ambilight I use the Kodi grabber addon (windows) as source. 

#### What is expected?
RAM usage stays on the same low level.

#### What is actually happening?
After 4 days hyperion uses more than 2 GB of RAM. 
I have attached two pmap outputs.

The first one is directly after the restart of the service (0,3 GB) and the second one is 4 days later (2,1 GB).

[fresh.txt](https://github.com/hyperion-project/hyperion.ng/files/8001300/fresh.txt)
[4days.txt](https://github.com/hyperion-project/hyperion.ng/files/8001303/4days.txt)

If you need any additional information, please ask. 
Thanks! 

#### System

Hyperion Server: 
- Build:           (HEAD detached at 2.0.12) (GitHub-dc6aa4d/df14958-1637501177)
- Build time:      Nov 21 2021 17:25:08
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.12
- UI Lang:         auto (BrowserLang: de-DE)
- UI Access:       expert
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Config path:     /root/.hyperion
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 3 (v7l)
- CPU Type:       Raspberry Pi 4 Model B Rev 1.1
- CPU Revision:   c03111
- CPU Hardware:   BCM2711
- Kernel:         linux (5.10.63-v7l+ (WS: 32))
- Root/Admin:     true
- Qt Version:     5.11.3
- Python Version: 3.7.3
- Browser:        Mozilla/5.0 (Linux; Android 8.0.0; SM-G930F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36

**Comment by Paulchen-Panther** [comment]
Hyperion is not exactly a small project. To find the memory hog, one would have to know what exactly you did in the 4 days. For example, to exclude the effect engine, you would have to turn off the start effect and the background effect and not use any effects during the 4 days. If the memory still fills up then it is another component.

**Comment by Lord-Grey** [comment]
@ManuVice Could you test, if that happens too, if you have smoothing off and maybe blackborder detection?

Smoothing is off when the LED-Device is off, therefore the issue might not be related to the device itself, but to the part between grabber and device.

On the Karate Code I have ad-hoc not seen any issue…

@darkcheater Would you mind sharing your configuration too. To see, if there are commonalities?

**Comment by ManuVice** [comment]
Thank you for reply. I have test it in past (February, March) with black bar detection and smoothing off and both off.
Next I have tried was deleting the config db and set only light and grabber new up. Same problem. Last thing I tried was only activate grabber and lights. If I activate lights the problem occurs. Grabber only is fine. 

Last version that worked for me was alpha 4 or 5.
I did a new setup in the end of 2021 and updated to the last versions. I didnt test the versions between those.

I have looked at the commits between the last versions but my code understanding is too bad.

My result is that the error has to do with lights enable.
Sorry for my bad english 😅

**Comment by Lord-Grey** [comment]
@ManuVice Thank you for the derailed summary. I will have another look.
Could you do me a favor and just change the LEDDevice to the debug file one?
Just to see, if it is related to the Serial Karate Device or not.

**Comment by ManuVice** [comment]
Thank you. I will do it tommorow.

If it helps I had created a forum thread with libleak enabled. Log is posted as attachment. 
This was the time I updated my RPi and hyperion. 

https://github.com/WuBingzheng/libleak

https://hyperion-project.org/forum/index.php?thread/12423-memory-leak/

**Comment by ManuVice** [comment]
@Lord-Grey I have set a new clean config with default settings up. Tested a few things. I have found an interesting thing.
If I set up "Capturing Hardware" "Frames per secound" to higher fps memory goes faster up. Hyperion will not free memory. It will eaten all up. If I disable "LED Output" on dashboard memory will get freed. I have added some screenshots.

If I set LED Output to file memory looks fine.
[hyperion file output.log](https://github.com/hyperion-project/hyperion.ng/files/8391878/hyperion.log)

Memory after new clean config
![1  hyperion config reset](https://user-images.githubusercontent.com/555893/161116956-c4537785-ebd9-4ba1-a9f7-421b7e01a604.png)

Memory after 2min with led output FILE
![2  led output file 2min](https://user-images.githubusercontent.com/555893/161117083-fb51277a-2aca-46fc-9315-1f7585d80c11.png)

Memory after 2min with Karate16
![3  led output karate16 2min](https://user-images.githubusercontent.com/555893/161117255-a8d8b2ac-13fb-477b-a4b7-27298e84d07c.png)

Memory after ~5min with Karate16 and 50fps 
![4  after a few minutes with led output enabled 50fps ](https://user-images.githubusercontent.com/555893/161117381-8866bd9c-bbf1-411a-99db-8688a0c519bb.png)

Memory after I disable led output in dashboard after ~5min 50fps
![5  after disable led output](https://user-images.githubusercontent.com/555893/161117493-ce771afa-ca84-4f55-9fc9-1987ba672a61.png)

[Hyperion debug config.txt](https://github.com/hyperion-project/hyperion.ng/files/8391908/Hyperion.config.txt)

**Comment by ManuVice** [comment]
I have set up a new device (odroid c2) with only hyperion on it. it uses right now 1,4gb of memory 🙈
my system memory + swap are going to burst

**Comment by Lord-Grey** [comment]
@darkcheater You are running your grabber  with encoding format MJPEG. 
Would it be possible to run with a different encoding format and see, if the memory leakage still persists?

Thank you!

**Comment by ManuVice** [comment]
I have an update on this issue. 
I have tested Raspbian and Dietpi images based on Debian Stretch, Bullseye and Bookworm bare metal installation, released versions and compiled hyperion ng myself. With all of them I had memory leaks.

I also tried various docker versions.. same issue.
Tested on RaspberryPi 3b, 4b and OdroidC2

But then I discovered [https://hub.docker.com/r/bradsjm/hyperion-ng-addon-aarch64](url) 
2.0.13, 2.0.14 and 2.0.15 are working fine over serveral weeks. 
2.0.15 is running since 2023-02-20 24/7 and memory is now at 14.8MB 👍

**Comment by seirowg** [comment]
I can confirm this also. Overnight my LXC container went from 250MB RAM usage to 520MB used. Newest version of Hyperion NG installed on Ubuntu 22.04 LXC container. Hyperion is set to only listen for Android grabber.

**Comment by Lord-Grey** [comment]
The issue was already open too long...
Luckily we found some time during the holidays to look into the memory issue and found a serious one which is fixes by #1678.
The finding was regarding each image processed and nicely correlates with @ManuVice's observations. Thank you for highlighting the scenario.

@darkcheater, @ManuVice, @jamieburchell, @seirowg and others
I would be really great, if you could test the fix.
In case you are brave you can also test #1679 which build further one the fix (just change the PR number in the instructions below.

### Testing the PR on Linux
0. Create a GitHub user, if case you have one continue with the next step
1. Create a fine grained personal access token for your GitHub user.
Go to https://github.com/settings/tokens?type=beta and do a "Generate new token":
a) Give the token a name
b) Select "All Repositories"
c) Under Permissions/Repository permissions
Define Read-Only Access to "Actions"
d) Generate token
2. Copy the new generated token
3. Log on to your Linux system, e.g. ssh into the HyperBian rpi
4. Execute the install_pr script replacing the token with your token copied in 2.
   `wget -qO- https://raw.githubusercontent.com/hyperion-project/hyperion.ng/master/bin/scripts/install_pr.sh | bash -s -- -t token 1678`

5. run the execution script to start Hyperion under the current user
   `./hyperion_pr1678/1678.sh`

6. Test the new build etc.

7. Remove  installed version for the given PR

**Note:** 
The script will stop the current hyperion service before execution.
After doing your tests, you should start the service again or just reboot to start the service automatically.
Replace USER with the username, Hyperion runs with.

`systemctl start hyperion@USER.service`

**Note 2:** 
In case you would like to test with a current configuration, provide the configuration location via the "-c" option. 
The configuration will be copied to avoid any side effects on your current configuration,
i.e. any updates to the configuration when testing the PR will also not be reflected in the current setup.

Sample

Current user
`wget -qO- https://raw.githubusercontent.com/hyperion-project/hyperion.ng/master/bin/scripts/install_pr.sh | bash -s -- -t token -c ~/.hyperion 1678`

**Comment by ManuVice** [comment]
Hi, I'am sorry but I cannot reproduce the memleak. I have tried some docker containers which had the memleak in past, but now they are working fine.
With the last version of HyperHDR I can reproduce it. I havent changed any hardware, so I dont know why it doesnt leak atm.

I will start some new tests with a fresh native install in the next days

**Comment by Lord-Grey** [comment]
@ManuVice Thanks for looking into it.
Note: HyperHDR changed lots of its codebase, therefore you cannot compare the outcome of the observations and the test.

**Comment by ManuVice** [comment]
I've set up my OdroidC2 with a fresh bullseye image, but I could not reproduce the memleak. I've also tested your PR and it worked fine, too.
I'am sorry, but I havent changed any hardware. I dont know why it works now.

Hopefully this PR will solve it for the others with this problem. Thank you for your hard work!!

**Comment by HexRebuilt** [comment]
Hello, i'm noticing a similar behaviour on macos v 2.1.1. after hours of use, the ram consumption reaches 3.5gb from the 53mb when first lunched.

Since i don't turn off the mac mini, at times, when i wake the system up, the application is not responsive or a new icon appears in the taskbar.
