### ISSUE TITLE
Config migrator for 1.x to 2.x configurations ?

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#146]
What are everyone's thoughts on this ?

Do we need one ?

Should we refuse to run if the config doesn't have a version string in it ?

Should we highlight "old" config sections and refuse to start ?

Personally I've been caught out running and old code only to find it still has a boot sequence statement in it!

**Comment by redPanther** [comment]
We definitly need strong schema validation, so an old config will fail to load. We can define a version in config and set valid value in json schema. Then we can be sure that we get no old stuff.

Migration .... don't know. For now I would say no, we have other things to do.

**Comment by brindosch** [comment]
Depending on how much work you invest it is possible or not, as the current configs for hyperion are very  inconsistent i would do a entire cut here.
People should delete and reinstall. Writing a "migration guide" is enough i think.

benefits:
- don't waste time on thinking about all available settings combinations and how to extend (migrate) them. For example "lost" settings, renaming, ... For sure this is no fun to program.

Instead of refuse we could think about
Error in schema -> restore hyperion.conig.json.default to keep Hyperion always alive. redPanther already spoke about to keep the webinterface alive and delay hyperion start/fixing issues or start in "save" mode.

**Comment by brindosch** [comment]
More or less dicussed, if someone is bored he could do it. But i take no responsibility for the results. I think the time is still wasted as 2.0 is a big breakpoint so rather work on something more important :)

(my opinion comes also along as i hacked around with our install .sh and i am sure this has the same fun of endless hours of issues /try and error). Due to the point you are forced to expect anything.
