### ISSUE TITLE
Add instance in websocket response to a subscription

### ISSUE THREAD

**Issue by pierrebuet** [hyperion-project/hyperion.ng#1504]
#### What problem does this feature solve?
The subscription via websocket to component changes on a system with more than one instance

#### What does the proposed API look like?
Include the instance name/number in the JSON response to a subscription to component changes. Now the API is responding with a command, with a component and with a state, but LEDDEVICE as an example can come from different instances with the same parameter name. A “LEDDEVICE true” as an answer to a websocket submission is then not enough, since I can’t know which instance was active at the time of the response to the subscription

#### How should this be implemented in your opinion?
Include the parameter instance and the instance concerned in the JSON response to a websocket submission for component changes

#### Are you willing to work on this yourself?
I’m not fit enough in the JSON API to help on this one.

**Comment by Lord-Grey** [comment]
Hey
I in general can follow the ask, but I think the request is based on the wrong assumption that one websocket subscription will listen to multiple instances responses.

Due to Hyperion's current (limited) design, one WebSocket deals with one instance only.

Sample: 

1. You open a WebSocket
2. You request a Subsciption, i.e. you subscribed to Instance 0
3. You execute an event in instance 0 
4. You get an update via the websocket
5. You execute an event in instance 1
6. You DO NOT get an update via the websocket, as it is bound to instance 0

If you want to get events for instance 1

1. You open a WebSocket
2. You do a Switch Instance to 1
2. You request a Subsciption, i.e. you subscribed to Instance 1
3. You execute an event in instance 0 
4. You DO NOT get an update via the websocket
5. You execute an event in instance 1
6. You get an update via the websocket, as it is bound to instance 0

-> via the same web-socket you will not receive updates for multiple instances.
Currently, you would need to have one socket per instance to monitor all events happening.

**Comment by pierrebuet** [comment]
I understand now that I have to open multiple sockets toward the same host, switch to every instances and open there every time a different subscription. When I then get a response, how can I connect the response to the given socket and then the instance? I understood from the api doc, I can pass a different parameter to each websocket, but the response to a subscription doesn’t include this parameter. Do I perhaps have misunderstood something in the doc of the API?

**Comment by Lord-Grey** [comment]
> how can I connect the response to the given socket and then the instance?

When you have a socket per instance sending requests, receiving responses and having your subscriptions for the given instance delivered to the same socket, you have a one-to-one relationship of socket and instance.
When you have a socket for instance 1 and get a subscription response on that socket, you already know it must be for instance 1. 
I do get get the question?

With the current (limited) API design of Hyperion, you would open one socket towards instance 0 and get the system details, i.e. number of instances.
Then you would create extra socket connections for each additional instance which will work as a pipe for requests/responses/subscriptions for a given instance.

>  I understood from the api doc, I can pass a different parameter to each websocket
You can pass different parameters, but not the instance per request.
That is why you need a socket per instance and during initialisation switch the socket to the instance you are working with.
If you do just request/response, you can go with one socket, but would need to always switch instancne before every command...

**Comment by pierrebuet** [comment]
Got it! Thank you so much for your patience. I’ll give it a try this way. You can then close the issue/enhancement from my side.

**Comment by Lord-Grey** [comment]
Thanks.
I might still do the enhancement, but wanted to be clear managing expectations on how the API and subscriptions are working.
