### ISSUE TITLE
WS281x LEDs - Must run as Root

### ISSUE THREAD

**Issue by specie77** [hyperion-project/hyperion.ng#1620]
- [x] I confirm that this is an issue rather than a question.

## Bug report
ttps://github.com/hyperion-project/hyperion.ng/blob/64642a44578fe48dce8144c23180d29c160c7906/bin/scripts/updateHyperionUser.sh#L88

Not working as designed.

#### Steps to reproduce
Execute updateHyperionUser.sh

#### What is expected?
The service OOTB runs as hyperion@**pi**.service

#### What is actually happening?
CURRENT_SERVICE is being written to memory as hyperion@**hyperion**.service

#### System

HyperBian 2.0.15 distro on a Pi 0W

**Comment by Lord-Grey** [comment]
> What is expected?
> The service OOTB runs as hyperion@pi.service

Unfortunately, your expectation is wrong.
The provider of rpiOS recommended to go away from the default user "pi" for security reasons.
Therefore the HyperBian image makes use of the default user "hyperion" since July 2022.
This user executes the hyperion service, too.

Given that service names are styled servicename@username.service and servicename and username are "hyperion" the outcome is a service named hyperion@hyperion.service.

**Comment by specie77** [comment]
Thats very strange, because mine ran OOTB hyperion@pi.service. Which is why line 88 didn’t work for me. If mine was running as hyperion@hyperion.service, line 88 would have run successfully.

I used the lastest 2.0.15 HyperBian image and the official Raspberry Pi imager from the Raspi website.

**Comment by Lord-Grey** [comment]
To investigate the case, I flashed a new [HyperBian](https://github.com/hyperion-project/HyperBian/releases/tag/HyperBian) and the service was running correctly as hyperion (not pi).
Would you mind doing a fresh install again; maybe on an extra sd-Card, please?
Just to investigate, if there is an OOTH fialure scenario which I missed.

**Comment by specie77** [comment]
Flashed a new SD card. Hyperion user, you were correct. No idea what I was doing wrong the first time, but seems right now.

Likely an ID10T user error. Sorry about that :)

**Comment by Thomas-Emmel** [comment]
No issue. Good that we jointly sorted this.
