### ISSUE TITLE
WS281x LEDs - Running as Root

### ISSUE THREAD

**Issue by specie77** [hyperion-project/hyperion.ng#1621]
#### What problem does this feature solve?

The updateHyperionUser.sh script was difficult to locate, I found it by digging through the github issues/comments.  I understand from previous issues and threads that Hyperion should not run as root unless WS281x LEDs are used.  

#### What does the proposed API look like?
N/A

#### How should this be implemented in your opinion?
To facilitate a more seamless end user experience, is it possible to trigger a webUI pop-up/warning (when selecting WS218x) to say "To use these LEDs, Hyperion will need to run as root, are you sure?" and if yes, execute updateHyperionUser.sh (pending the outcome of https://github.com/hyperion-project/hyperion.ng/issues/1620)

#### Are you willing to work on this yourself?
Don't have the relevant expertise, otherwise I would.

**Comment by Lord-Grey** [comment]
Thanks for highlighting that the user experience can improved!

> The updateHyperionUser.sh script was difficult to locate

You can invoke updateHyperionUser (without .sh) from everywhere in the system (as it is in the PATH), if Hyperion was installed via its package. This is the case for HyperBian.
I apprechiare that it would be helpful to have this outlined in the official documentation.
As the project currently lack contributors, we are happy to get further support in completing the documentation.


> To facilitate a more seamless end user experience, is it possible to trigger a webUI pop-up/warning (when selecting WS218x)

The envisioned UI behaviour was implemented before, but due some bug it unfortunately does not resolve correctly.
I will address this bug.

Actually the screen should look like this, if hyperion does not run under root for this device:
![image](https://github.com/hyperion-project/hyperion.ng/assets/48840279/c071a20f-0663-44dc-94c9-6d77420e9005)

**Comment by Lord-Grey** [comment]
I fixed the issue via #1623 .

May I ask you testing the fix?
You should be able to do this in a quite simple way due to a new script....

1. As you are already a GitHub user ,create a fine grained personal access token for your user.
Go to https://github.com/settings/tokens?type=beta and do a "Generate new token":
a) Give the token a name
b) Select "All Repositories"
c) Under Permissions/Repository permissions
Define Read-Only Access to "Actions"
d) Generate token
2. Copy the new generated token
3. ssh into the HyperBian rpi
4. Execute the install_pr script replacing the token with your token copied in 2.
   `wget -qO- https://raw.githubusercontent.com/Lord-Grey/hyperion.ng/Update_platforms/bin/scripts/install_pr.sh | bash -s -- -t token 1623`

5. run the execution script to start Hyperion without root access
   `~/hyperion_pr1623/1623.sh`

6. Check that the UI reports missing admin access and does not allow configuring ws281x

7. run the execution script with sudo to start Hyperion with root access
   `sudo ~/hyperion_pr1623/1623.sh`

8. Check that the UI reports allows to configure ws281x

9. Remove  installed version for the given PR

**Note:** 
The script will stop the current hyperion service before execution.
After doing your tests, you should start the service again or just reboot to start the service automatically.
`systemctl start hyperion@root.service`

**Note 2:** 
In case you would like to test with a current configuration, provide the configuration location via the "-c" option .

Sample

Current user
`wget -qO- https://raw.githubusercontent.com/Lord-Grey/hyperion.ng/Update_platforms/bin/scripts/install_pr.sh | bash -s -- -t token -c ~/.hyperion 1623`

root user
`sudo wget -qO- https://raw.githubusercontent.com/Lord-Grey/hyperion.ng/Update_platforms/bin/scripts/install_pr.sh | bash -s -- -t token -c /root/.hyperion 1623`

**Comment by specie77** [comment]
Step 4 didn’t seem to do anything, and step 5 said no file found.Not sure what I missed. I successfully created a token and replaced the word token with my actual token.Happy to help and test, please let me know what I’m missing.On Jul 18, 2023, at 10:54 AM, LordGrey ***@***.***> wrote:﻿
I fixed the issue via #1623 .
May I ask you testing the fix?
You should be able to do this in a quite simple way due to a new script....


As you are already a GitHub user ,create a fine grained personal access token for your user.
Go to https://github.com/settings/tokens?type=beta and do a "Generate new token":
a) Give the token a name
b) Select "All Repositories"
c) Under Permissions/Repository permissions
Define Read-Only Access to "Actions"
d) Generate token


Copy the new generated token


ssh into the HyperBian rpi


Execute the install_pr script replacing the token with your token copied in 2.
wget -qO- https://raw.githubusercontent.com/Lord-Grey/hyperion.ng/Update_platforms/bin/scripts/install_pr.sh | bash -s -- -t token 1623


run the execution script to start Hyperion without root access
~/hyperion_pr1623/1623.sh


Check that the UI reports missing admin access and does not allow configuring ws281x


run the execution script with sudo to start Hyperion with root access
sudo ~/hyperion_pr1623/1623.sh


Check that the UI reports allows to configure ws281x


Remove  installed version for the given PR


Note:
The script will stop the current hyperion service before execution.
After doing your tests, you should start the service again or just reboot to start the service automatically.
systemctl start ***@***.***
Note 2:
In case you would like to test with a current configuration, provide the configuration location via the "-c" option .
Sample
Current user
wget -qO- https://raw.githubusercontent.com/Lord-Grey/hyperion.ng/Update_platforms/bin/scripts/install_pr.sh | bash -s -- -t token -c ~/.hyperion 1623
root user
sudo wget -qO- https://raw.githubusercontent.com/Lord-Grey/hyperion.ng/Update_platforms/bin/scripts/install_pr.sh | bash -s -- -t token -c /root/.hyperion 1623

**Comment by Lord-Grey** [comment]
I am really sorry, but the path of different activities just crossed unfortunately.
Exactly yesterday, I merged the development branch (where the link in 4. pointed to) and it got deleted.
The script is now available in the official repository.

I updated the command in step 4. and it should work now.
Sorry for the inconvenience.

**Comment by Lord-Grey** [comment]
@specie77 It would be great, if you could have another try with the updated link.

**Comment by specie77** [comment]
Updated link?Sent from my iPhoneOn Jul 29, 2023, at 1:31 PM, LordGrey ***@***.***> wrote:﻿
@specie77 It would be great, if you could have another try with the updated link.

**Comment by Lord-Grey** [comment]
I updated the initial instructions with the correct link. But the artifacts are gone now.
I will merge the PR and you then can test the Nightly build, an own build or a build of an upcoming PR

**Comment by InaudibleSound** [comment]
Any update on this? I stuck on this step too, it shows me this: Information
Hyperion must run with 'root' privileges for this controller type!
I've followed your steps, but it says Error : Unauthorized 

<img width="1380" height="599" alt="Image" src="https://github.com/user-attachments/assets/7868669b-0edb-4c1b-98fd-8ee187ae0ad8" />

**Comment by Lord-Grey** [comment]
As the error message says, the token you provided is not valid. It looks too short.

**Comment by InaudibleSound** [comment]
well, that's the token, but when i paste the token it won't download anything. 
What am I missing? 
wget -qO- https://raw.githubusercontent.com/Lord-Grey/hyperion.ng/Update_platforms/bin/scripts/install_pr.sh | bash -s -- -t token -c ~/.hyperion 1623

Is the token that: https://raw.githubusercontent.com/Lord-Grey/hyperion.ng/Update_platforms/bin/scripts/install_pr.sh
If that's right, then i should change it to my one right? Sorry for the spam, just don't get it to work and stuck here.

**Comment by Lord-Grey** [comment]
Never  post your tokens here. Those are your keys to GitHub activities.

You need to replace the „token“ text with your full token text.

And your command should be in one line

**Comment by InaudibleSound** [comment]
Thank you for deleting the token from my post! 
i've got so far, can you please check what am I doing wrong? Do I mess somewhere with the commands?
Tahnk you in advance! 

<img width="943" height="165" alt="Image" src="https://github.com/user-attachments/assets/5aa740ab-0e54-44ab-aec8-446f0ab0ad43" />

**Comment by Lord-Grey** [comment]
> Thank you for deleting the token from my post! i've got so far, can you please check what am I doing wrong? Do I mess somewhere with the commands? Tahnk you in advance!
> 

The Pull Request #1623 was merged already two years ago and does not exist any longer…

I suggest you install the nightly build, if you would like to test a current build.

Installing PR builds is for testing dedicated development versions.
If you are keen to do this, you can test #1933

**Comment by InaudibleSound** [comment]
well, I've managed to do that really fast:
the method I used was:
SSH into RPi
sudo systemctl hyperion
sudo systemctl --disable hyperion@pi.service
sudo systemctl enable --now hyperion@root.service

This worked for me and I was able to run the service as a root.
