### ISSUE TITLE
change hyperion.service file install script bug?

### ISSUE THREAD

**Issue by ctugt** [hyperion-project/hyperion.ng#246]
Hi after using the installing scripts i couldnt get it to start at boot.

I had to change in hyperion.service file in systemd folder two options
user=hyperion
group=hyperion

to

User=%i
Group=%i

in order to get the systemd file working

**Comment by ctugt** [comment]
so i think you need to change hyperion.ng/bin/service/hyperion.systemd.sh

**Comment by penfold42** [comment]
I don't think %i is the right approach.
Isn't that the instance name ?

Do you have a Hyperion user created ?
What if you use root instead of hyperion ?

**Comment by redPanther** [comment]
I use:
[Unit]
Description=Start hyperion Server
After=network.target
After=fadecandy.service
 
[Service]
ExecStart=/opt/hyperion/bin/hyperiond /opt/hyperion/hyperion.config.json
 KillMode=process
Restart=always
 
[Install]
WantedBy=multi-user.target

But thst is optimized for my setup. In h.ng the suportive files (install/service) arnt in sync with current development. They are more or less the last things we care.
We will making a new install procedure,  when most tasks for new hyperiond finished.

Currently I suggest to compile, copy and configure it manually. Note: current version dont need effects folder, just copy hyperiond executable to /usr/bin. To install default config run: 
mkdir /etc/hyperion
hyperiond --export-config /etc/hyperion/hyperion.config.json

And because this is hot development, we garantee nothing, please keep that in mind when using that.

**Comment by ctugt** [comment]
root did the job also ;) but the default hyperion not, proberly cause i dont have hyperion user in ubuntu. so i think we need to change this default value, or i need to put this in my personal documentation if ever have to start over

**Comment by ctugt** [comment]
only thing now is, i cleaned install and did you tips just compile no install, and when i place hyperion.service in system/system folder it doesnt run auto on reboot, i can start it with systemctl start hyperion manually in terminal

**Comment by ctugt** [comment]
im proberlymissing one step that the install.hyperion script did for  me could you help me? then im done xD

**Comment by ctugt** [comment]
i found this information 	systemctl enable hyperion.service in thehyperion.install scripts, i ran the command to enable the hyperion.service file and it worked after reboot!

**Comment by brindosch** [comment]
@redPanther 
Well, in case we get more requests i stop the cron jobs, as these builds plopping up at sourceforge (or we upload them "restricted" somewhere else).
