### ISSUE TITLE
rather an question than an issue add custimized shutdown2 script

### ISSUE THREAD

**Issue by ctugt** [hyperion-project/hyperion.ng#247]
mm i see that we don't need the effects folder to cp anymore, but could you guys please add shutdown2.py (its the same as the original shutdown, without the 3 times blinking), which makes it an awesome boot effect for me/us.

atm i still need to manually cp it to usr/share/hyperion/effects.

Here is the files

[effects.zip](https://github.com/hyperion-project/hyperion.ng/files/478207/effects.zip)

**Comment by brindosch** [comment]
you could still load effects via effects folder.
Overall: It would be better to modify the old .py with a additional boolean that enables a real shutdown if wanted (and probably skips the effect)

The effect system is powerfull, just use it and create a PR if you are done :)
Basic informations: https://hyperion-project.org/wiki/a-Effect-development

**Comment by redPanther** [comment]
> with a additional boolean that enables a real shutdown if wanted

already in since I add the effect.

just copy the shutdown.json in effects folder and modify script filename with leading :
--> this:

{
	"name"   : "System Shutdown",
	"script" : ":shutdown.py",
	"args"   :
	{
		"speed"            : 1.2,
		"alarm-color"      : [255,0,0],
		"post-color"       : [255,174,11],
		"shutdown-enabled" : false
	}
}

**Comment by brindosch** [comment]
oh. never had a closer look, sorry :)

**Comment by redPanther** [comment]
and when set both colors to black, then it looks like no effect

**Comment by ctugt** [comment]
no what im sating is that i use the customized shutdown2.py as a boot script

**Comment by redPanther** [comment]
Then make a pr with your effect. But please dont name it shutdown .... be more creative

**Comment by ctugt** [comment]
What is an pr and yes I can rename it to startup but still need permission from the author cause it's his script with some lines removed. Do you know who made it? I tried to find out but couldn't find the author

**Comment by redPanther** [comment]
I made it ... a pr is a pull request. This hyperion repository is mainly for developers.

**Comment by redPanther** [comment]
I reviewed your modification and I disagree. It is the wrong way to do what you want. It duplicates most of the code - this is always wrong! Why you don't add an option to disable the alert color? Should be about 2 lines of python code and one line of json.

Behind code lines are always an idea. For this one the idea was to make it possible to shutdown the pi via hyperion android app. The alert effect is the countdown to abort, when accidentally selected on remote. I made shutdown function as an option and set to false, because user who don't understand what the shutdown effect is for, don't accidentally shutdown the system.

So from your code I think your intention was to make an effect that enlightens the leds from bottom top top. Yeah that's cool, why not - but then it should be more clean, creative and versatile. E.g.
- remove the shutdown code
- give a speaking name that describes what it does
- add an option for fill direction - in degrees would be very nice to have a "fill effect" e.g. diagonal 
-  what about a gradients
- or looping
- or ...

... thats what I mean, changing a parameter is more or less a personal thing - everybody can do this. We want cool things, not the x variant of what we already have ...

**Comment by ctugt** [comment]
I would love to have that, but i have no such skills as you guys, im pretty prout of my setup atm but this toughes the sky for me, thats why i made an request for it, i know copy the code is a bad idea, but this was the only way i could get it to work. Would you please mind to make such an booteffect, i tought the name launch woult fit.

Anyway if you have no such time, which i respect, cause this hyperion project is awesome. I would like to have you personal approval to edit youre file for local use only. i wont share the customized script. My friend also say its really awesome without the blinking as an startup. (i also implented it in autoexec.py) each time i start a movie i will let it "initiate to start".

**Comment by tpmodding** [comment]
you can post it in our forum if you want
