### ISSUE TITLE
extend the kodi checker to off/capture/effect options?

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#350]
Should we look to extend the kodi checker beyond true/false to off/capture/effect options?

**Comment by redPanther** [comment]
Other idea would be to remove kodichecker and make kodi addon more inteligent. The kodi plugin knows best about kodi state. There could be a list of states with combobox behind to set the action.
If state is reached in kodi plugin the desired action will be triggered over json

**Comment by brindosch** [comment]
I think adding more to this highers the complexity a lot. Also you reach the limits for expansion very fast. For a maximum customisation there is no way around for eventing triggers and commands from within a kodi addon.

(also due to some weird information sharing from kodi json rpc)
Works Kodi 17 now properly regading json feedback? My last test some months back was horrible /entirely broken.

**Comment by redPanther** [comment]
I close this for same reasons as #401 and things @brindosch said.  Would love to remove kodi things from hyperion and do all the magic from a kodi addon

**Comment by brindosch** [comment]
What i could imagine are "extensions" written in python that are optional/ could be downloaded via ui.
Like the effects configurator we render the ui based on json schema which provides options. 
The python script itself could maintain connection/eventing of 3rd parties or open a own port where you could push information to.

Depending on your settings and the events information, the python script could push actions to Hperion.

I understand that it's not possible to implement everywhere a Hyprion extension. Or it is just comfortable to have all in one place.
But this is nothing for the coming weeks.
