### ISSUE TITLE
move getoptplusplus to (qt5) QCommandLineParser

### ISSUE THREAD

**Issue by redPanther** [hyperion-project/hyperion.ng#39]
as we are moved to qt5 there are new capabilities we can use from qt5.
Currently we use a 3th party lib called getoptplusplus to parse command line options.

Now we can use qt commandline parser and delete getoptplusplus from our code.

doc: http://doc.qt.io/qt-5/qcommandlineparser.html

**Comment by brindosch** [comment]
Crazy, do we need a list to find everything? :D

**Comment by brindosch** [comment]
Debian 8
QT5.3
So this should be the limit for now :)

**Comment by brindosch** [comment]
Could we place somewhere a min qt version check before it trys to compile? Should prevent further issues ot better finding where is the error source really

**Comment by redPanther** [comment]
we should stay on 5.2 for now. ubuntu 14.04 LTS has 5.2.1. This ubuntu is often used ...

**Comment by WoLpH** [comment]
Well, I've started on this issue but I'm not sure how to proceed with the more advanced commandline parsing. The `hyperiond` command is fairly simple but the `hyperion-remote` command has some more advanced type checking... to handle this using a `QCommandLineOption` I would either need to extend the `QCommandLineOption` to support a `QValidator` or I need to manually validate it in the class.

Any preference for one or the other?
I'm personally voting for extending the classes to support type checking but it might be a bit over the top. Manually validating using a `QValidator` is fairly trivial anyhow so that is an option as well.

**Comment by WoLpH** [comment]
The progress so far: https://github.com/WoLpH/hyperion.ng/tree/qcommandlineparser

**Comment by redPanther** [comment]
>  but it might be a bit over the top. 

we are on extending the json api a lot. hyperion-remote is our reference json client and I guess the command args will grow ... 
If you can do the big solution - it would be perfect. If you have only time/... for the trivial solution, than this would be also great.

BTW because we move lots of things to QT only, we should slightly use more QString where it is possible/useful.

**Comment by redPanther** [comment]
@WoLpH 
I see you use relativ include paths. Pleas don't do that.
I mean this:
`#include "../../include/commandlineparser/CommandLineParser.h"`
you should use
`#include <commandlineparser/CommandLineParser.h>`

**Comment by WoLpH** [comment]
Those were auto added by clion. My local development branch doesn't have them anymore. No worries :)

**Comment by WoLpH** [comment]
> Could we place somewhere a min qt version check before it trys to compile? Should prevent further issues ot better finding where is the error source really

We do. Our cmake configuration limits our compilation to Qt5.2 and above

**Comment by brindosch** [comment]
Just as notice, this was 2 months before :)
After this message redPanther added it

**Comment by WoLpH** [comment]
Ah, didn't know :)
