### ISSUE TITLE
Persist led layout settings in config

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#395]
Would be good to have.

1) browser persistence isn't great if I change devices

2) some effects could do with knowing some of this info (clockwise, gaps, height and width.
The could be reverse engineered from the config as it stands but it would be horrible code

Obviously non standard layouts would have to default to NA or -1 if they make no sense.

**Comment by brindosch** [comment]
For the second point i won't count on it. For a proper eff development you need values you could count on.
Also the logic behind to make sure that they are set to non sense values and if they are set make sure that the led creation switches into a fallback.

I you ask me, it is not worth the work, but @redPanther should leave a mind here :)

**Comment by redPanther** [comment]
effects should based on image. Then all orientation stuff solves automatically.
For the clock effect: I want to merge light-clock and clock. I want add a param "faces" then we can have different clock faces. currently "artistic" and "analog". Before merge, I have to add line drawing to effect backend. (I also want to add all basic primitives)

**Comment by brindosch** [comment]
Yes the image thing, i didn't understood how this really works.
Merging is good.

/closed

**Comment by redPanther** [comment]
some stuff about image data in our effect engine:

we have 2 image implementations. I would call it 
1. "raw python"
2. "qpainter buffer"

image in general: you have an image with e.g. 40x25 pixel. This is projected onto leds in the same way as we project an image from grabber onto the leds. A pixel consists of 3 byte (RGB).

1) The image is stored in an array with size width x height x 3 bytes (e.g. 40x25x3=3000). Then you operate on that array to set rgb pixels you wish. E.g. to make a snake that crawl around your screen you have to set the outer pixel of the image.
If you set a pixel in the center of the image, then you will see this only if you have leds there (normale only on matrix layout)
The dificult thing is, that the 2D image must be accessed in an 1D array. 
example image size: 2x2
image:
```
(0,0,0) (255,255,255)
(255,255,255) (0,0,0) 
```
array representation:
```
0,0,0,255,255,255,255,255,255,0,0,0
```

Normally you access a pixel by x,y values and get the rgb color. But with 1D array you have to transform your x|y position to position in image array.
``` 
r = imageArray[ width*y*3 + x*3 ]
g = imageArray[ width*y*3 + x*3 + 1 ]
b = imageArray[ width*y*3 + x*3 + 2 ]
```

see knight rider effect for an example

2) The image is stored in a QImage and is not direct accessible throught python (it is stored in the parent c++ effect object that runs the python effect). You can call operations from python to modify the image. Currently only gradient stuff is implemented. But the method to process is the same as 1). Make modifications to the image (draw pixels, points, rects, circles, gradients, ....) and then this image will be projected to leds
This method has some advantages:
- faster, because we do the heavy things in c++
- more complex stuff possible, because we can use Qt's powerful painting stuff
- easier to use. no dealing with image raw data, just set the params you want and go ...

disadvantage:
- is some wanted drawing method not implemented in backend (currently e.g. setPixel or line drawing), then there is no chance to do it from python effect code (due to the lack of raw access to image data)

see light-clock for an example (the hyperion.image... stuff are the methods to modify the QImage buffer)

**Comment by brindosch** [comment]
Ah nice, thank you looking forward for c++ implementations :)
