### ISSUE TITLE
Delay after start

### ISSUE THREAD

**Issue by tpmodding** [hyperion-project/hyperion.ng#484]
as here described: https://hyperion-project.org/threads/no-commands-sent-to-atmoorb.162/#post-8057

is it possible to add an value/solution for this problem?

**Comment by penfold42** [comment]
If Hyperion depends on a network being up, this should be solved using OS init scripts.

Depending on your platform, this will be different but setting a dependency on the network is the right way

**Comment by brindosch** [comment]
You can test the systemd file, which depends on network. But not sure if this is already enough.
However a good led device corrects issues on it's own. AtmoOrb shouldn't quit if target not reachable on startup. What happens if you restart the atmoorb, is it also broken afterwards?

So you see, the device should handle this out of the box gracefully. That a network is not reachable or the target is shortly offline is a common case (might it be bad wlan or short power outage)

**Comment by brindosch** [comment]
Systemd has the after-network-target which is currently part or it.
If there is something atmoorb specific during runtime the leddevice needs to handle that
Closed for the moment
