### ISSUE TITLE
Chromecast Support

### ISSUE THREAD

**Issue by sachaw** [hyperion-project/hyperion.ng#498]
Add support to capture chromecast streams possibly through the api?
https://developers.google.com/cast/docs/reference/

**Comment by MartB** [comment]
I doubt that its possible to intercept / capture streams using the official api.

However it could be possible to write a chrome cast receiver application that takes the videos and uses the experimental html5 <video> capture api (if supported) to extract the frames of non content protected videos.

Due to the limited use case and the obvious complexity i wont give this a go to.
Maybe someone else is up to the challenge.

**Comment by sachaw** [comment]
yea, your second ideas was about what I was thinking, have hyperion act as a receiver and then cast its input to the real chromecast.

**Comment by penfold42** [comment]
This feature won’t be incorporated directly in Hyperion.

An external chromecast proxy that sends capture data like the existing external grabbers would be cool

**Comment by MartB** [comment]
Just to clarify i meant a receiver application running on the chromecast.

**Comment by sachaw** [comment]
oh, I see, that could actually work a lot better, although would you would need platform integration for whatever you want to watch.

**Comment by tpmodding** [comment]
I will close this, this is not planned for now...we have a lot of other things to fix and implement
