### ISSUE TITLE
Colors: Fix minLuminance, add enable/disable option (also during runtime)

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#59]
Option: Set the min luminance just during grabbers are active, so it will be diabled if you use a "idle effect/color" or just black with disabled grabbers.
For this you may "move" this to another(new?) component which could be also called (started and stopped) during runtime.

Fix: my ambient light get strange colors at black areas. Looks weird. Another solution is appreciated.
Hint: The old deprecated value "blacklvl" works like a charm, but might be more a hack. As long it works?

**Comment by redPanther** [comment]
color transformations can't be started/stopped. You can think like that that:

- grabbers are like a cd-player, there you can start/stop/pause
- effect engine are like a tuner (you can select your "programm")
- color transforms are more like the equalizer. You can bypass it, but not start/stop
- color smoothing is more like a dsp that can make nice echo/reverb effects. (bypass only)
- all things go into the priorityMuxer. This is somehow like the channel switch on the amp (tuner,phono,cd,aux), but with detection if a channel plays music. if not auto switch to next input source
- The leddevice is like an amp
- and the leds itself are like the speakers.

in conclusion you can start/stop only components that produces images or led colors (setimage/setcolors)

Is your wish that luminance settings only applied to grabbers? ATM we can't decide from where the colors comming from and in a way we will never do. But we can change the place where this specific settings are applied. One possible solution: apply this directly after the grabber before it goes to muxer - downside: this works as long as protoserver is only used for grabber data - or better say, we can't decide if it comes from proto or from grabber and which type is proto sender.
Currently we have only grabbers as proto sender ... 

ATM we don't have "bypass" for our transformations.  In our hifi-set picture means that:
If you don't want the EQ then disconnect all cables and throw it away. If you need it, buy a new one and connect it. This is a bit to dramatic - a bypass switch in  the EQ would perform better :-)
This means e.g. for color smoothing. This component should always be in our chain. When "disabled" (=bypassed) then this component write all input data directly to the output.

**Comment by penfold42** [comment]
The more I think about it, I'm thinking we need 2 sets of transforms.

One for the LEDs and one for the grabbers.

Each have specific reasons for needing some transform and with multiple sources and multiple receivers a single transform will get confusing 

On a related topic - colororder.
This probably needs to move from the core and be pushed closer to the led devices

**Comment by redPanther** [comment]
You mean input dependend transform settings? We have only one output so no need for specific output settings.
Currently transforms are last step before led output.

**Comment by brindosch** [comment]
There is only one reason for a "second" calibration channel - v4l2 because of the often D-A transcoded garbage. At least i think so.

**Comment by redPanther** [comment]
I mentioned it elsewhere, but to be complete here again:

Having multiple transforms is generally possible. The easiest way (without changing the code to much) is that a color transform are assigned to a specific priority channel. This is a bit like assigning different color transforms to specific leds, but on another level.

The configuration could look like that:

```
"color" :
	{
		"channelAdjustment" :
		[
			{
				"id"   : "default",
				"leds" : "*",
				"assignedPriority" : "",  /// or if this line is not present
				........
			},
			{
				"id"   : "grabber",
				"leds" : "*",
				"assignedPriority" : "901",
				........
			}
		],

```
And of course desired grabber must use prio channel 901 to get this working (in this example). This approach is not exactly the initial suggestions, but the best we can do without changing to much.
The diff is that we assign transform to a specific priority channel instead to a specific component. If another component (like an effect triggered by android remote) sends on this channel, then transformation applied to this component too.
This is not a big prob, because all input devices/components that can be used at the same time shouldn't send on same prio channel.

The other way, assigning transform directly to e.g. v4l is not so easy, because current data flow is, that transformations applied after prioMuxer and there we haven't the  info from which component the current data comes. But as I said, this isn't a big problem and prio-channel IDs configured in config, so we have full control ...

**Comment by brindosch** [comment]
Assignment to priorities should be nice
More or less a duplicate now of https://github.com/hyperion-project/hyperion.ng/issues/276

/closed
