### ISSUE TITLE
[Idea for discussion] Make hyperion a OBS sink

### ISSUE THREAD

**Issue by funnym0nk3y** [hyperion-project/hyperion.ng#630]
Hi, 

I am following your project for a few month now in hope to implement a solution for my PC running Windows. In the process of reading I came across the issue of having a grabber implementation for each operating system. To reduce development effort I had the idea to use OBS as a grabber with a capturing profile optimized for hyperion. This would add more flexibility and maybe eliminate some hardware solution. As I haven't contributed to the project yet that proposal should be seen as a naive idea.

regards 
funnym0nk3y

**Comment by brindosch** [comment]
Hello @funnym0nk3y ,
sadly there is currently no windows version of Hyperion available. As Hyperion is mostly based on [Qt](https://www.qt.io/) a port should be "easy". OBS sounds interesting as capture interface if it can "wrap" different platforms. Linux can be critical (looking at amlogic/RPi), so that might be a limit.

- Tune Hyperion (mostly CMAKE) for Windows and create instructions to setup dev env. (Note: There is a Qt grabber, which should capture images also on windows (speed might/will be horrible))
- Add OBS as additional capture interface

Open for contributions and questions :)

**Comment by b1rdhous3** [comment]
A OBS capture interface would be a great addition imho. So a user can use windows and stream the desktop, movies, games etc with obs to the hyperion instance. 

I think we should not hassle with hyperion on windows. There is enough work with the current supported OS's. Also I think most people would use linux for this anyway.

**Comment by brindosch** [comment]
Oh, if we just talk about streaming you can use HyperionScreenCap for Windows or the browser streaming feature of the webui (just available with https://IP:8092 due to browser restrictions)

@b1rdhous3 we need to talk about how to motivate people :)

**Comment by tpmodding** [comment]
@brindosch wie schauts damit aus? soll das noch bleiben, oder ist die windows version der ersatz?

**Comment by brindosch** [comment]
Good question!
Can be a valid feature request, the windows version doesn't have a directx capture

**Comment by Lord-Grey** [comment]
Addressed by https://github.com/hyperion-project/hyperion-obs-plugin
