### ISSUE TITLE
v4l2 add shutdown detection

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#7]
https://hyperion-project.org/threads/v4l2-add-shutdown-detection.146/

**Comment by redPanther** [comment]
why we dont use the signal threshold detection already build in v4ls grabber?

```
    -t, --signal-threshold <arg> The signal threshold for detecting the presence of a signal. Value should be between 0.0 and 1.0.
        --red-threshold <arg>    The red signal threshold. Value should be between 0.0 and 1.0. (overrides --signal-threshold)
        --green-threshold <arg>  The green signal threshold. Value should be between 0.0 and 1.0. (overrides --signal-threshold)
        --blue-threshold <arg>   The blue signal threshold. Value should be between 0.0 and 1.0. (overrides --signal-threshold)

```

**Comment by redPanther** [comment]
Already existing no signal detection works as expected - as long as your hardware produces a mono color picture when signal is lost. 

I will rework perhaps extend those code a bit, nevertheless this issue can be closed, because wanted feature works

**Comment by brindosch** [comment]
Sad that a improvement is not that easy.
But this is one of the points where  software  hits  the limit

**Comment by redPanther** [comment]
just to make this complete:

good settings for grabber with:

**black no signal picture**
redSignalThreshold"   : 0.1,
"greenSignalThreshold" : 0.1,
"blueSignalThreshold"  : 0.1

**black and/or blue no signal picture**
redSignalThreshold"   : 0.1,
"greenSignalThreshold" : 0.1,
"blueSignalThreshold"  : 1.0

**black and/or green no signal picture**
redSignalThreshold"   : 0.1,
"greenSignalThreshold" : 1.0,
"blueSignalThreshold"  : 0.1

I will close this, because it works and we can't do anything better in software
