### ISSUE TITLE
Some effects are running extreme slowly. 

### ISSUE THREAD

**Issue by b1rdhous3** [hyperion-project/hyperion.ng#757]
- [x] I confirm that this is an issue rather than a question.

## Bug report

Some effects seem to run very slowly. I just started a effect with file led device or Philips hue entertainment and on both it is running very slow in visualization on webUi. They are also running slowly on the led device. 
I have tested PR build 2.0.0-alpha.4-PR#592 and 2.0.0-alpha.3-PR#746. Effects which are slow for example are: Rainbow Swirl Fast, Police Lights solid. Candle seems to be normal. 

The Platform Capture is running smoothly. Both on Visualization and Hue Bulb it self (or file device).

#### Steps to reproduce

Open Visualization on Webui. 
Start one of above effects

#### What is expected?

Effects running smoothly. 

#### What is actually happening?

Sometime the color change takes seconds. 

#### System

Hyperion Server: 
- Build:       (HEAD detached at pull/746/merge) (GitHub-f1b80234/7dc53554-1585314697)
- Build time:  Mar 27 2020 13:14:58
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.3-PR#746
- UI Lang:     de (BrowserLang: de-DE)
- UI Access:   expert
- Avail Capt:  osx,qt

Hyperion Server OS: 
- Distribution: 
- Arch:         x86_64
- Kernel:       darwin (18.6.0 (WS: 64))
- Browser:      Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

**Comment by T-IOOO** [comment]
I can confirm some laggy experience aswell. I am using the online remote and it takes a while for the effects to load. I am currently using alpha.3

**Comment by b1rdhous3** [comment]
2.0.0-alpha.3-PR#712 is running smoothly. This was tested on RPi0 with raspbian.

**Comment by brindosch** [comment]
I can't repro that. Based on reports i guess a performance problem _somewhere_
@Lord-Grey @Paulchen-Panther

**Comment by Lord-Grey** [comment]
@b1rdhous3, @T-IOOO  Thanks for highlighting and pointing toward that issue.
It is related to a [fix ](https://github.com/Lord-Grey/hyperion.ng/commit/3f885eac58b696c044cbb58dd9f566dda2718579) I did before avoiding devision by zero failures, if latchtime= 0...

The reason is that we now allow a latch-time =0
When calculating the time between two updates (sleepTime) the minimum step-time gets zero.
A stepTime of zero is not allowed therefore, the sleep/update time interval is set to one second.
If you look at the output of the file-device with timestamps on, you will see that, too (assuming smoothing is off). Effects based on fade.py, random.py, swirl.py, traces.py are effected.

I would suggest to set sleeptime = 0.001, if latchtime = 0, this is the same as latchtime = 1
This will result in the smallest update time of 1 ms.

Below is the "Rainbow Swirl Fast" effect's code, if you would like following the explanation above. 

```
def getSTime(rt, steps = 360):
	rt = float(rt)
	sleepTime = max(0.1, rt) / steps

	# adapt sleeptime to hardware
	minStepTime= float(hyperion.latchTime)/1000.0

	if minStepTime == 0: minStepTime = 1
	if minStepTime > sleepTime:
		sleepTime = minStepTime
	return sleepTime

```

**Comment by brindosch** [comment]
That's a good catch! I think effects should never be influenced by that in any way.
