### ISSUE TITLE
Black color instead of OFF

### ISSUE THREAD

**Issue by Teryon** [hyperion-project/hyperion.ng#761]
# Feature request
Make Json/RPC black color diseappear from the source selection

#### What problem does this feature solve?
I'm using a plugin in homebrige to get hyperion LED Device in Homekit, but when I want to shut down the Led Device, it send black color (100 priority), so from this moment plateform capture (250 priority) doesn't work anymore without going to remote control and delete json/rpc black color source selection.

**Comment by Lord-Grey** [comment]
@Teryon Hi, not sure, if I do get the problem.

To switchOff/On and LedDevice you should use following hyperion JSON-Command, rather than issuing a "write Black" command.

{
 "command":"componentstate",
 "componentstate":{
   "component":"LEDDEVICE",
   "state":false
 }
}

I do not see that this is an hyperion.ng issue, but it would requires fixing in the component that issues the "write black" command.

**Comment by Lord-Grey** [comment]
I lately changed some LedDevices that they really switch off rather than sending "Black", too.
I suggest you test first, if disabling the LedDevice via the Remote Control UI works for your device.
In case your device still writes "black" output after disabling, please come back to me and we have a look what is missing in hyperion.ng supporting a "real" switch-off" on our end.
Here, I would more details about what device you are using and what is the device's configuration.

**Comment by Teryon** [comment]
I'm using this plugin : https://github.com/Danimal4326/homebridge-hyperion, so that I can control hyperion from Home (iOS) through Homekit/Siri.
I can see some function that set color to black to power off, I don't know how to modify this to send an OFF function instead.
That's why I thought it was a good thing to get rid of black color source, so that plateform capture could work again.

**Comment by Lord-Grey** [comment]
There seems to be another plug-in at
https://github.com/firsttris/homebridge-hyperion-light using
https://github.com/firsttris/hyperion-js-api

but this also is following the logic of writing "Black" rather than switching a device properly.
Last commits on all repositories are dated 2017/2019, so maybe not maintained an longer.
You may give it a try to open an issue there.

Alternatively, I leave this issue open and we can have a look, to fork one of the above.

**Comment by Teryon** [comment]
I gave up and I've migrated to Home Assistant.
