### ISSUE TITLE
UDP Still sending packets while Hyperion Instance is disabled

### ISSUE THREAD

**Issue by Sousanator** [hyperion-project/hyperion.ng#783]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I'm using udpraw LED device type and I noticed UDP packets are still getting sent out even though LEDDEVICE is disabled or that Hyperion Instance is disabled (Dashboard > Smart Access).  

The value of the data is full of 0s, but there should be no data being sent so it doesn't get confused with receiving black

#### Steps to reproduce
- under LED Hardware set controller type to udpraw
- set IP address to PC running wireshark
- enable/disable Hyperion (Dashboard > Smart Access)
- see that udp packets are still being sent while Hyperion is disabled

#### What is expected?
- udp packets should not be getting sent out while Hyperion is disabled or LEDDEVICE is disabled

#### What is actually happening?
- This is related to 'Refresh time' in the udpraw controller type
- Everytime it's supposed to refresh a packet gets sent out regardless if the instance, or LEDDEVICE is disabled
- Setting Refresh time to 0 fixes this, but then you lose the ability to tell if Hyperion is still enabled

#### System

Hyperion Server: 
- Build:       master (GitHub-072bee1/3a2b58b-1587481685)
- Build time:  Apr 23 2020 17:03:37
- Git Remote:  https://github.com/hyperion-project/hyperion.ng.git
- Version:     2.0.0-alpha.5
- UI Lang:     auto (BrowserLang: en-US)
- UI Access:   expert
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (4.19.97-v7+ (WS: 32))
- Browser:      Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0

**Comment by Lord-Grey** [comment]
@Sousanator 

The symptom you describe is the currently expected behavior for Refresh Time > 0.

Background of Refresh Time:

There are currently LedDevices out there which are not able maintaining a color over time.
Those devices need a refresh every other time interval to show a stable behavior.
A refresh time > zero will take care that the last color set will be sent to the LedDevice again, if no update happens in the given refresh time interval.

As for some devices (incl. UDP-RAW) there is not specific switch-off/on routine (API,...), the switch-off  is done by writing a one time "BLACK" output to the LedDevice and further updates are stopped.
In case of refresh-time > 0, the LedDevice requires to refresh itself with that "BLACK" item to maintain a stable state. That is why you see "BLACK" update packages for rewirtes and none for no rewrite.

For all network devices, I would expect that rewrite time is always = 0, as the client side (LedDevice) should be self-sufficient. All other newer devices, e.g. Hue, Nanoleaf, Yeelight, etc, do not have a color problem and even provide native switch-off/on commands (which are used by hyperion.ng). 
I would agree that it may be misleading to then even have that configuration item available per default (I will open an issue for that). 

Hope that outlines that from my perspective a refresh-time > 0 is not an expected configuration in the given scenario. In case, I missed out a scenario where it would be applicable, please come back to me.

**Comment by Sousanator** [comment]
Ah, that makes sense then if it shouldn't even be there.  I figured disabled would treat the instance as if it was not there and this seemed to be overlooked.  If it's something people expect to be on under special circumstances then you're right, default should be 0 to avoid confusion.

I'll leave mine at 0 and close this issue
