### ISSUE TITLE
Language selection with the respective language (WebUI)

### ISSUE THREAD

**Issue by Paulchen-Panther** [hyperion-project/hyperion.ng#787]
#### What problem does this feature solve?
Clearer language selection

#### What does the proposed API look like?
Nothing API. WebUI only

#### How should this be implemented in your opinion?
I don't know if our WebUI UTF8 is capable of showing this. As an example, I noticed the Firefox Language Pack page
Screenshot:
![Feature Request](https://user-images.githubusercontent.com/16664240/80832557-2a375200-8bed-11ea-9add-6b4083642c2b.png)

#### Are you willing to work on this yourself?
I don't speak JavaScript

**Comment by brindosch** [comment]
So you want
- english - native

Hm, this requires to load all lang files if we want to use our own translations. A list with just these keys would be better. But as we don't "build" the ui there is no step for such a task

@b1rdhous3

**Comment by Paulchen-Panther** [comment]
No. Like this:
https://prnt.sc/s9czst
The first part should also be written in bold

**Comment by Lord-Grey** [comment]
Hi

looking at the general guidance on language switchers, the language item should be in the local language rather than in Englisch and a translation, see

![image](https://user-images.githubusercontent.com/48840279/80865197-04ab5680-8c88-11ea-8da9-a8e132776d1c.png)

It may be even easier to implement, if we have a static list of languages hyperion supports....

**Comment by Lord-Grey** [comment]
Closed by #812
