### ISSUE TITLE
Protobuf dependency

### ISSUE THREAD

**Issue by NicoHood** [hyperion-project/hyperion.ng#89]
More a question:
Can't we drop the protobuf submodule and use a packaged protobuf?

https://packages.debian.org/search?keywords=protobuf
https://www.archlinux.org/packages/extra/x86_64/protobuf/

At least for arch, would this package work, or is it too old/wrong? Because then I could at least manually remove the protobuf submodule and use the internal library to save some space.

**Comment by penfold42** [comment]
Does openelec/libreelec include it ?

**Comment by NicoHood** [comment]
I do not know, but I found this:
https://github.com/LibreELEC/LibreELEC.tv/tree/master/packages/addons/addon-depends/protobuf

Maybe we could add protobuf submodule as fallback, but normally use the package version?

**Comment by brindosch** [comment]
Check it out, test it and if it works create a PR :)
> to save some space

This is really minor as you already mentioned and we have enough open building zones that needs attention. So i would suggest to participate a little bit :)

**Comment by NicoHood** [comment]
For what is the protobuf required? Maybe we can disable it for some builds anyways.

I am currently looking into it. Its possible the submodule is not required.

**Comment by redPanther** [comment]
protobuffer is main ipc for image data. what problem you have with submodule? I realy don't understand it. This won't install anything on your system, it is only buildtime dependency ... 
This aproach is better than using system protobuf, because e.g. on arch pkg build we have to install protobuf before compilation and remove afterwards - but only when no other packages need it.

**Comment by NicoHood** [comment]
`-DUSE_SYSTEM_PROTO_LIBS` In the cmake command seems to make it work :)

Using a make dependency is normal. This way we can get the most up to date protobuf and need no submodule. We also dont have a copy for avahi etc.

**Comment by penfold42** [comment]
no, the spi driver simply uses /dev/spidev0.0 - no other libraries/modules needed

**Comment by NicoHood** [comment]
And `rpi_ws281x @ dfcf740`? I guess we have to keep this submodule for rpi at least.

FYI my current PKGBUILD can be found here in the comments: https://aur.archlinux.org/packages/hyperion/

**Comment by redPanther** [comment]
I added the DUSE_SYSTEM_PROTO_LIBS for the libreelec people, because they want to compile there package and otherwise they wont support hyperion.
Please use the submodule, it wont hurt anybody and this is the default way to do - we didn't want and we absolutely can't support any possible way.
We  use protobuf 2.3 and google realesed 3.0 beta, so we can't guarantee that they are compatible.

It's good that you build a pkgbuild, but don't do it in a way that we - the hyperion team - wont support - otherwise all your users of your pkgbuild won't get support

**Comment by brindosch** [comment]
Regarding LibreELEC support is also a problem. It looks like we need our own install method anyway. With the webinterface at least the usage would be the same doesn't matter which platform you are. But if people use not "our" deps this may result in strange issues

**Comment by brindosch** [comment]
Hm, we could talk about an update if we may get certain benefits. 
Could be closed
