### ISSUE TITLE
Hue Entertainment mode does not resume after no signal

### ISSUE THREAD

**Issue by jaffacake** [hyperion-project/hyperion.ng#930]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Hue Entertainment doesn't re-enable after no signal/turning off input and then restarting again. I have to go into the Hyperion UI & open the LED Hardware page & click save for it to drive the LEDs again

#### Steps to reproduce
Setup Hue Entertainment, send some content. 
Turn off input device/trigger black screen timeout
Turn input device back on

#### What is expected?
Hyperion should resume updating Hue Entertainment lights 

### What is actually happening?
Hyperion no longer updates the Hue Entertainment lights

#### System
Hyperion Server: 
- Build:       (HEAD detached at ffa2fd45) (Paulchen-Panther-69e9fa6d/ffa2fd45-1595517126)
- Build time:  Jul 24 2020 15:55:19
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.7
- UI Lang:     auto (BrowserLang: en-GB)
- UI Access:   advanced
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (5.4.51-v7l+ (WS: 32))
- Browser:      Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36

**Comment by jaffacake** [comment]
I've also noticed a couple times I've had to go back into the Wizard & reselect the Entertainment Group for it to restart

**Comment by Lord-Grey** [comment]
@jaffacake Thanks for reporting.
It is a known issue.

**Comment by jaffacake** [comment]
I can see a PR mentioned this issue & has been merged? Does it fix this issue? I can help test if required. I've had my setup off as I'm waiting for this to be fixed.

**Comment by Lord-Grey** [comment]
@jaffacake The current issue that the Hue-Device does not resume after itself detected a black light scenario has not been fixed.
This is currently due to the fact that a proper, generic design would be that the input device detects missing input and then signals that scenario and lights are turned of. Not that every individual device would do such a checks.

With #960 some groundwork was done that in case there is no input stream in the priority list, the configured LED device will go off or on (if a new stream continues).
You might want testing it by disabling the "Platform capture" via the Remote Control. Take case that there is no background effect configured, plus disable switch off on black at your Hue device.

The Source selection list should be empty:
![image](https://user-images.githubusercontent.com/48840279/96337572-7df90300-1088-11eb-986c-99f8243d9c1c.png)

Note the LED device still shows "Enabled",as it is working. Only the state changed which is off.
Running in Debug mode, you should see the following log-line:
`2020-10-17T14:55:33.274 hyperiond HYPERION     : <DEBUG> Hyperion.cpp:541:handlPriorityChangedLedDevice() | No source left -> switch LED-Device off
`

Would be be good to better understand what is your scenario/setup when describing"Turn off input device/trigger black screen timeout"  in steps to reproduce.
