### ISSUE TITLE
webUI - "look and feel"

### ISSUE THREAD

**Issue by T-IOOO** [hyperion-project/hyperion.ng#998]
Just a little touch-up for the webUI that needs to be fixed.

![image](https://user-images.githubusercontent.com/59575587/92443809-4efe9000-f1b2-11ea-8f11-198b7d7f6b9a.png)

![image](https://user-images.githubusercontent.com/59575587/92443902-72293f80-f1b2-11ea-986b-3c0975f47d91.png)

**Comment by Paulchen-Panther** [comment]
Unfortunately I have to close your issue. Why?
Here is the explanation: This visual flaw is not caused by Hyperion. First, Bootstrap is responsible for this, and second, the length of the word. Here is a proof of the official site:
![Screenshot_2](https://user-images.githubusercontent.com/16664240/92511556-c1e92480-f20d-11ea-8c0e-00c1410b3225.jpg)
If you know a web dev who could fix this bug in Hyperion (Bootstrap), you can suggest that you apply here:
https://hyperion-project.org/threads/web-devs-needed.10716/
